Tasks/task2
Filliny/altexsoft-lab-2020 pull request #2
Opened 2020-08-21 06:41 UTC by Filliny

Тестовые файлы в папке с солюшеном.

2020-08-26 15:12 UTC, alex-geraschenko requested changes

2020-08-26 15:12 UTC, alex-geraschenko commented on Recipes/Recipes/Views/RecipeView.cs
> +        private IStorageContext Storage { get; }
Нет смысла делать приватные свойства. Достаточно будет приватных полей

2020-08-26 15:12 UTC, alex-geraschenko commented on Recipes/Recipes/Views/RecipeView.cs
> +        private IStorageContext Storage { get; }
Используйте UnitOfWork или конкретный репозиторий, а не сонтекст напрямую

2020-08-26 15:12 UTC, alex-geraschenko commented on Recipes/Recipes/Views/TopView.cs
> +        private string LastHead { get; set; }
Нет смысла делать приватные свойства. Достаточно будет приватных полей

2020-08-26 15:12 UTC, alex-geraschenko commented on Recipes/Recipes/Views/TreeView.cs
> +        private IViewSettings Settings { get; }
Нет смысла делать приватные свойства. Достаточно будет приватных полей

2020-08-28 07:11 UTC, serhii-shkodenko commented on Recipes/Recipes/Controllers/UnitOfWork.cs
> +        private IFileWriter _writer;
Можно добавить модификатор только для чтения для полей, инициализируемых в конструкторе.

2020-08-28 07:19 UTC, serhii-shkodenko commented on Recipes/Recipes/Controllers/StorageContext.cs
> +    public interface IStorageContext
Я бы выделил интерфейс `IStorageContext` в отдельный файл, так как может потребоваться поделиться контрактом, а у Вас он идет вместе с реализацией, а на другой платформе возможны нюансы с хранением данных. Почему объекты для работы с данными находится у Вас в неймспейсе `Recipes.Controllers` и в папке `Controllers`?

2020-08-28 14:29 UTC, Filliny commented on Recipes/Recipes/Controllers/UnitOfWork.cs
> +        private IFileReader _reader;
хорошо.

2020-08-28 15:04 UTC, Filliny commented on Recipes/Recipes/FileHandler/IngredientsRepository.cs
> +            if (existing != null)
хорошо

2020-08-28 15:05 UTC, Filliny commented on Recipes/Recipes/FileHandler/RecipeRepository.cs
> +            if (existing != null)
хорошо

2020-08-28 15:05 UTC, Filliny commented on Recipes/Recipes/FileHandler/IngredientsRepository.cs
> +            if (existing != null)
хорошо

2020-08-28 15:05 UTC, Filliny commented on Recipes/Recipes/FileHandler/RecipeRepository.cs
> +            if (existing != null)
хорошо

2020-08-28 15:10 UTC, Filliny commented on Recipes/Recipes/Models/Category.cs
> +        public ICategory GetParent()
да, вы правы

2020-08-28 15:11 UTC, Filliny commented on Recipes/Recipes/Models/Category.cs
> +        public void SetParent(ICategory parent)
fixed

2020-08-28 15:12 UTC, Filliny commented on Recipes/Recipes/Models/IDataserializable.cs
> +    public interface IDataserializable
JsonIgnore

2020-08-28 15:13 UTC, Filliny commented on Recipes/Recipes/FileHandler/RecipesSelector.cs
> +            return Selected;
Понял

2020-08-28 15:14 UTC, Filliny commented on Recipes/Categories.json
> +  "DbFilename": "Categories.json",
поправил

2020-08-28 15:14 UTC, Filliny commented on Recipes/Categories.json
> +        "ChildrenCategories": [
Переписано на plain relation

2020-08-28 15:15 UTC, Filliny commented on Recipes/Ingredients.json
> +  "DbFilename": "Ingredients.json",
fixed

2020-08-28 15:15 UTC, Filliny commented on Recipes/topmenu.json
> +  "DbFilename": "topmenu.json",
fixed

2020-08-28 15:17 UTC, Filliny commented on Recipes/Recipes/FileHandler/CategoriesRepository.cs
> +            throw new NotImplementedException();
не определился что реализовывать для вложенной структуры... с листом стало понятно что реализовывать ( то же что и для остальных)

2020-08-28 15:21 UTC, Filliny commented on Recipes/Recipes/Controllers/StorageContext.cs
> +    public interface IStorageContext
Спасибо за комментарий  - да, разнесение интерфейсов и реализаций равно как расположение файлов в неймспейсах пока еще хромает)  Так же как и нейминг собственно) Поправим

2020-08-28 15:22 UTC, Filliny commented on Recipes/Recipes/Controllers/UnitOfWork.cs
> +        private IFileWriter _writer;
Да - верно, спасибо)

2020-08-28 19:56 UTC, Filliny commented on Recipes/Recipes/Views/TreeView.cs
> +        private IViewSettings Settings { get; }
fixed

2020-08-28 19:56 UTC, Filliny commented on Recipes/Recipes/Views/TopView.cs
> +        private string LastHead { get; set; }
fixed

2020-08-28 20:38 UTC, Filliny commented on Recipes/Recipes/Views/RecipeView.cs
> +        private IStorageContext Storage { get; }
fixed

2020-08-28 20:40 UTC, Filliny commented on Recipes/Recipes/Controllers/UnitOfWork.cs
> +        public IStorageContext Context => storage;
fixed

2020-08-28 20:41 UTC, Filliny commented on Recipes/Recipes/FileHandler/IngredientsRepository.cs
> +            Ingredient existing = _storageContext.IngredientsFile.IngredientsList.First(r => r.Id == id);
implemented generic abstract class

2020-08-28 20:41 UTC, Filliny commented on Recipes/Recipes/FileHandler/IngredientsRepository.cs
> +            Ingredient existing = _storageContext.IngredientsFile.IngredientsList.First(r => r.Id == item.Id);
implemented generic abstract class

2020-08-28 20:41 UTC, Filliny commented on Recipes/Recipes/FileHandler/RecipeRepository.cs
> +            Recipe existing = _storageContext.RecipesFile.Storage.First(r => r.Id == item.Id);
implemented generic abstract class

2020-08-28 20:41 UTC, Filliny commented on Recipes/Recipes/FileHandler/RecipeRepository.cs
> +            Recipe existing = _storageContext.RecipesFile.Storage.First(r => r.Id == id);
implemented generic abstract class

2020-08-28 20:42 UTC, Filliny commented on Recipes/Recipes/Models/Ingredient.cs
> +    public class Ingredients : IDataserializable
fixed

2020-08-28 20:42 UTC, Filliny commented on Recipes/Recipes/Navigation/KeyReader.cs
> +    class SimpleReader : IKeyReader
fixed

2020-08-28 20:42 UTC, Filliny commented on Recipes/Recipes/Models/Recipe.cs
> +    public class RecipesList : IDataserializable
fixed

2020-08-28 20:48 UTC, Filliny commented on Recipes/Recipes/Views/ItemsView.cs
> +        private IViewSettings Settings { get; }
fixed

2020-08-28 20:48 UTC, Filliny commented on Recipes/Recipes/Views/RecipeCreatorView.cs
> +        private IUnitOfWork FileUnit { get; }
fixed

2020-08-28 20:50 UTC, Filliny commented on Recipes/Recipes/Views/ItemCreator.cs
> +            Ingredient newIngredient = new Ingredient();
done

2020-08-28 20:50 UTC, Filliny commented on Recipes/Recipes/Views/ItemCreator.cs
> +        private IRepository<Ingredient> Storage { get; }
fixed

2020-08-28 20:51 UTC, Filliny commented on Recipes/Recipes/Views/ItemChooseView.cs
> +            Storage = fileWorker.Context;
исправил

2020-08-28 20:51 UTC, Filliny commented on Recipes/Recipes/Navigation/ListNavigator.cs
> +        private IKeyReader KeyReader { get; set; }
fixed

2020-08-28 20:52 UTC, Filliny commented on Recipes/Recipes/FileHandler/TopMenuRepository.cs
> +            throw new NotImplementedException();
не определился что реализовывать для вложенной структуры... с листом стало понятно что реализовывать ( то же что и для остальных)

2020-08-31 10:51 UTC, alex-geraschenko requested changes
1. `IFileReader` и `IFileWriter` я бы объединил в какой-нить `IFileManager`
2. Местами код переусложнен. Постарайтесь следовать принципам KIS и DRY

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Categories.json
> +  "CategoryList": [
Объект `CategoriesList` избыточен. Достаточно хранить только список категорий

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Categories.json
> +      "ParentCategoryId": 0,
Можно упростить имя свойства до `ParentId`

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Categories.json
> +      "ChildIds": [
Список `ChildIds` избыточен

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Ingredients.json
> +  "IngredientsList": [
Объект `IngredientsList` избыточен. Достаточно хранить только список ингридиентов

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes.json
> +  "Storage": [
Объект `Storage` избыточен. Достаточно хранить только список рецептов

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/FileHandler/FileReader.cs
> +    public interface IFileReader
Интерфейс лучше вынести в отдельный файл, чтобы он хранился отдельно от реализации

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/FileHandler/FileWriter.cs
> +    internal interface IFileWriter
Интерфейс лучше вынести в отдельный файл, чтобы он хранился отдельно от реализации

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/FileHandler/IStorageContext.cs
> +        void Dispose();
Для этого метода существует интерфейс `IDisposable`

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/FileHandler/StorageContext.cs
> +            if (!this._disposed == false)
Это выражение можно упростить

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/topmenu.json
> +  "TopArticles": [
Объект `TopArticles` избыточен. Достаточно хранить только список категорий

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/topmenu.json
> +      "ParentCategoryId": 0,
Можно упростить имя свойства до `ParentId`

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/topmenu.json
> +      "ChildIds": [
Список `ChildIds` избыточен

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/Views/TopView.cs
> +    internal interface ITopView
Интерфейс лучше вынести в отдельный файл, чтобы он хранился отдельно от реализации

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/Views/RecipeCreatorView.cs
> +    internal interface IRecipeCreatorView
Интерфейс лучше вынести в отдельный файл, чтобы он хранился отдельно от реализации

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/Views/ItemsView.cs
> +    internal interface IItemsView
Интерфейс лучше вынести в отдельный файл, чтобы он хранился отдельно от реализации

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/Views/ItemCreator.cs
> +    internal interface IItemCreator
Интерфейс лучше вынести в отдельный файл, чтобы он хранился отдельно от реализации

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/Views/ItemChooseView.cs
> +    internal interface IItemChooseView
Интерфейс лучше вынести в отдельный файл, чтобы он хранился отдельно от реализации

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/Navigation/ListNavigator.cs
> +    internal interface IListNavigator
Интерфейс лучше вынести в отдельный файл, чтобы он хранился отдельно от реализации

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/Models/Settings.cs
> +    internal interface IViewSettings
Интерфейс лучше вынести в отдельный файл, чтобы он хранился отдельно от реализации

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/Models/IDataserializable.cs
> +    public interface IDataserializable
А какой вообще смысл в этом интерфейсе ?

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/Controllers/MainController.cs
> +                if (mainMenuItem.Id == 1) //working with recipes
Можно заменить на `switch`

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/Controllers/MainController.cs
> +                    if (recipeCategory != null)
Если инвертировать условие, то можно уйти от одного уровня вложенности

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/FileHandler/FileReader.cs
> +        public IDataserializable ReadFile<T>()
Лучше возвращать `T`, а не `IDataserializable`

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/Models/IRelational.cs
> +    public interface IRelational
Вместо этого интерфейса лучше использовать базовый класс модели

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/Models/IListable.cs
> +        string Name { get; set; }
Это свойство лучше вынести в базовый класс модели

2020-08-31 10:51 UTC, alex-geraschenko commented on Recipes/Recipes/Views/Description.cs
> +            MemberInfo[] memInfo = type.GetMember(enumElement.ToString());
Постарайтесь найти решение без использования рефлексии

2020-08-31 20:33 UTC, Filliny commented on Recipes/Categories.json
> +  "CategoryList": [
Согласен. Стараюсь двигаться к упрощению...

2020-08-31 20:42 UTC, Filliny commented on Recipes/Categories.json
> +      "ParentCategoryId": 0,
Done!

2020-08-31 20:43 UTC, Filliny commented on Recipes/Ingredients.json
> +  "IngredientsList": [
Спасибо! Изменил!

2020-08-31 20:43 UTC, Filliny commented on Recipes/Recipes/FileHandler/FileReader.cs
> +    public interface IFileReader
Done

2020-08-31 20:47 UTC, Filliny commented on Recipes/Recipes/FileHandler/FileWriter.cs
> +    internal interface IFileWriter
Done!

2020-08-31 20:48 UTC, Filliny commented on Recipes/Recipes/FileHandler/IStorageContext.cs
> +        void Dispose();
Fixed

2020-08-31 20:50 UTC, Filliny commented on Recipes/Recipes/FileHandler/StorageContext.cs
> +            if (!this._disposed == false)
так

2020-08-31 20:50 UTC, Filliny commented on Recipes/topmenu.json
> +      "ParentCategoryId": 0,
Done!

2020-08-31 20:50 UTC, Filliny commented on Recipes/topmenu.json
> +  "TopArticles": [
Fixed

2020-08-31 20:51 UTC, Filliny commented on Recipes/Recipes/Views/TopView.cs
> +    internal interface ITopView
Done!

2020-08-31 20:51 UTC, Filliny commented on Recipes/Recipes/Views/RecipeCreatorView.cs
> +    internal interface IRecipeCreatorView
Done!

2020-08-31 20:52 UTC, Filliny commented on Recipes/Recipes/Views/ItemsView.cs
> +    internal interface IItemsView
Done!

2020-08-31 20:52 UTC, Filliny commented on Recipes/Recipes/Views/ItemCreator.cs
> +    internal interface IItemCreator
Done!

2020-08-31 20:53 UTC, Filliny commented on Recipes/Recipes/Views/ItemChooseView.cs
> +    internal interface IItemChooseView
Done!

2020-08-31 20:53 UTC, Filliny commented on Recipes/Recipes/Navigation/ListNavigator.cs
> +    internal interface IListNavigator
Done!

2020-08-31 20:55 UTC, Filliny commented on Recipes/Recipes/Models/Settings.cs
> +    internal interface IViewSettings
Done!

2020-09-01 07:13 UTC, Filliny commented on Recipes/Recipes/Controllers/MainController.cs
> +                if (mainMenuItem.Id == 1) //working with recipes
Done

2020-09-01 07:14 UTC, Filliny commented on Recipes/Recipes/FileHandler/FileReader.cs
> +        public IDataserializable ReadFile<T>()
да - лучше IList<T>. Спасибо)

2020-09-01 07:20 UTC, Filliny commented on Recipes/Recipes.json
> +  "Storage": [
Solved

2020-09-01 11:04 UTC, Filliny commented on Recipes/Categories.json
> +      "ChildIds": [
removed

2020-09-01 11:45 UTC, Filliny commented on Recipes/Recipes/Models/IRelational.cs
> +    public interface IRelational
Согласен. Изменил

2020-09-01 11:45 UTC, Filliny commented on Recipes/Recipes/Models/IListable.cs
> +        string Name { get; set; }
Изменил

2020-09-01 11:50 UTC, Filliny commented on Recipes/Recipes/Controllers/MainController.cs
> +                    if (recipeCategory != null)
да - согласен)

2020-09-01 17:27 UTC, Filliny commented on Recipes/Recipes/Views/Description.cs
> +            MemberInfo[] memInfo = type.GetMember(enumElement.ToString());
switch....

2020-09-01 18:22 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-09-01 18:26 UTC, merged